apiVersion: apps/v1
kind: Deployment
metadata:
  name: eks-app-deployment
  labels:
    app: eks-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: eks-app
  template:
    metadata:
      labels:
        app: eks-app
    spec:
      containers:
      - name: eks-app
        image: <ECR_REPO_URI>:<IMAGE_TAG>
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: eks-app-service
spec:
  selector:
    app: eks-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer
